os: osx
osx_image: xcode9.4
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x
    - SKIP_LATEX_BUILD=1
    - TOXENV=py39
    - IS_PYTHON=true

install:
  - brew install imagemagick
  - pip3 install -U tox codecov

script:
  - if [ $IS_PYTHON = true ]; then tox -- -v; fi
  - if [ $IS_PYTHON = false ]; then npm test; fi

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi

notifications:
  email: false
