version: 2
jobs:
  build:
    docker:
      - image: sphinxdoc/docker-ci
    working_directory: /sphinx
    steps:
      - checkout
      - run: /python3.6/bin/pip install -U pip setuptools
      - run: /python3.6/bin/pip install -U .[test,websupport]
      - run: make test PYTHON=/python3.6/bin/python
